### ISSUE TITLE
Participant 7 markers

### ISSUE THREAD

**Issue by henryclever** [ostadabbas/SLP-Dataset-and-Code#1]
Hi,

I believe that the markers are flipped horizontally on participant 7 in the dataset. I.e. when you look at a pressure image/depth image/etc where the head is facing 'up', the markers are flipped side to side. This is 7/102 (not hospital setting). 

-Henry

**Comment by ShuangjunLiu** [comment]
Hello, Henry.
I check the 7th subject as following.
For 'uncover' case, there are 45 poses / person.
The 7th in range  45*6 + 1 ~  45 * 7  =  271~ 315.

I checked random skeleton in this range as follows.
[cid:53a04e5f-4f09-4a6a-a490-aa86fc02c2ce]

From the test, it seems to be correct.
You can add the code snippet circled in red  to eg_SLP_interface.ipynb to try it out.

Thanks.



________________________________

**Comment by henryclever** [comment]
Hi Shuangjun,

I'm sorry, but I can't see the code snippet circled in red. I'm also not sure what the '[cid:53a04e5f-4f09-4a6a-a490-aa86fc02c2ce]' code is for. Actually, I wasn't able to get the ipynb working. It's probably just some issue on my side and I haven't dug into it enough yet. However, I was able to get the main.py network to train (well almost.. my GPU RAM is too small but otherwise it runs up to a point), and import your image calibrations and data into another visualization script that I wrote. Here are some pictures that might help to show the issue I'm experiencing.

Take for example, Subject 1, pose 2 uncovered. Here is the RGB image:
![image_000002_small](https://user-images.githubusercontent.com/7378478/93713521-806c4980-fb2a-11ea-93cc-0a5956240e85.jpg)


And here is the pressure image, the calibrated depth image, and the markers. By calibrated, I mean that I used your transform to align the markers and the depth image with the pressure image. So the pressure image aligns by the identity matrix, and the depth image aligns with another matrix that you provided. All good. I tested this visualization on all 102 subjects and it aligns quite well (except for subject 7).
![subject_1_pose2_uncover](https://user-images.githubusercontent.com/7378478/93713262-9f69dc00-fb28-11ea-91a8-50d559f72657.png)


On the other hand, take for example Subject 7, pose 2, uncovered. here is the RGB image:
![image_000002_small](https://user-images.githubusercontent.com/7378478/93713531-8b26de80-fb2a-11ea-971b-532ea99ac154.jpg)

And here is the pressure image calibrated depth image, and the markers. Observe that the pressure image makes sense following the RGB, but the depth image is flipped as are the markers. You can tell that the markers are also flipped (i.e. the person would in the prone posture), because the violet skeleton links are now on the left when facing the picture. The violet skeleton links represent the person's left arm and left leg, whereas the green links represent the right side.
![subject7_pose2_uncover](https://user-images.githubusercontent.com/7378478/93713413-b0671d00-fb29-11ea-85be-279721141e59.png)

It appears that the raw depth .png images in the 'depth' folder do not suffer from this problem for participant 7. So given that notion, perhaps there is some issue with the calibration matrix?

**Comment by henryclever** [comment]
Thanks!
Henry C.
