### ISSUE TITLE
Data augmentation - shifting

### ISSUE THREAD

**Issue by henryclever** [ostadabbas/SLP-Dataset-and-Code#2]
Hi, 

The paper indicates that among data augmentation steps, there is shifting (for images and targets, I'm assuming). Is this implemented in the code? Line 190 in the "SLP_FD.py" script is the following:

`scale, rot, do_flip, color_scale, do_occlusion = get_aug_config()`

However, I don't see shifting among these. If it is implemented, do you know where it is? Did you do shifting on the paper results?

Thanks!
Henry C.

**Comment by ShuangjunLiu** [comment]
Thank you for your keen eyes.
Shift is not implemented in this version.  We will revise the statement.
________________________________

**Comment by henryclever** [comment]
OK! Sounds good. Thanks for the clarification!

-Henry
